// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250422135836_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Telefon",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "IPhone 15",
                            Price = 100000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "eraregatgtrAW",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "IPhone 15",
                            Price = 200000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "reafgagr",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Name = "IPhone 15",
                            Price = 300000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "4tgwerw3erhy",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "IPhone 15",
                            Price = 400000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Description = "wre4tfa",
                            ImageUrl = "5.jpg",
                            IsActive = true,
                            Name = "IPhone 15",
                            Price = 500000m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
